screens 19-21 updated and added
Hudhud/Job_Bazaar pull request #84
Opened 2019-12-09 18:41 UTC by mo3ni

#79  
screen 19 updated 
screens 20-21 added

2019-12-09 19:14 UTC, atila29 requested changes
Please update branch. And use Task model instead of DocumentSnapshot.

2019-12-09 19:14 UTC, atila29 commented on lib/models/task.dart
> +//import 'package:cloud_firestore/cloud_firestore.dart';
why these comments?

2019-12-09 19:14 UTC, atila29 commented on lib/models/task.dart
>  import 'dart:convert';
Why change this file?

2019-12-09 19:14 UTC, atila29 commented on lib/screens/detail_page.dart
> +        case 1:
Why do something in this case?

2019-12-09 19:14 UTC, atila29 commented on lib/screens/pay_screen.dart
> +  final DocumentSnapshot task;
Use the Task model instead of DocumentSnapshotQuery

2019-12-10 11:48 UTC, atila29 approved these changes

2019-12-10 11:52 UTC, elvarlax approved these changes

2019-12-10 11:52 UTC, elvarlax commented on lib/models/task.dart
>  import 'dart:convert';
Fix this

2019-12-10 11:52 UTC, elvarlax commented on lib/models/task.dart
> -      o.id == id &&
Don't change this, only the code you are adding

2019-12-10 12:16 UTC, merged